version: '3.9'
services:
  dev-db:
    image: postgres:16.0
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Qwerty1!
      POSTGRES_DB: expense_db
    ports:
      - 5434:5432
  redis:
    image: redis:7
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8081:8081
  # test-db:
  #   image: postgres:16.0
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: Qwerty1!
  #     POSTGRES_DB: expense_db
  #   ports:
  #     - '5435:5432'
    # volumes: 
    #   - db:/var/lib/postgresql/data
# volumes:
#   db:
#     driver: local
